apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  serviceName: redis-headless
  replicas: 2
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
        - name: redis
          image: "{{ .Values.Statefulset.imageURL }}:{{ .Values.Statefulset.imageVersion }}"
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          component: redis
          project: roboshop
          tier: database
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 2Gi