apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - protocol: TCP
      port: 6379 
      targetPort: 6379