
apiVersion: v1
kind: Service
metadata:
  name: catalogue # service name
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app
  ports: 
  - name: http
    protocol:  TCP
    port: 8080 # service port
    targetPort: 8080 # container port